let fishMapping = new Map([
    ["aquaculture:arapaima","starcatcher:lush_pike"],
    ["aquaculture:pacific_halibut","starcatcher:sandtail"],
    ["aquaculture:atlantic_cod","starcatcher:stonefish"],
    ["aquaculture:atlantic_halibut","starcatcher:garnet_mackerel"],
    ["aquaculture:atlantic_herring","starcatcher:blue_herring"],
    ["aquaculture:bayad","starcatcher:ironjaw_herring"],
    ["aquaculture:blackfish","starcatcher:dusktail_snapper"],
    ["aquaculture:bluegill","starcatcher:bluegigi"],
    ["aquaculture:boulti","starcatcher:deepjaw_herring"],
    ["aquaculture:muskellunge","nomansland:billhook_bass"],
    ["aquaculture:brown_shrooma","starcatcher:sporefish"],
    ["aquaculture:brown_trout","starcatcher:agave_bream"],
    ["aquaculture:capitaine","starcatcher:mirage_carp"],
    ["aquaculture:carp","starcatcher:pale_carp"],
    ["aquaculture:red_shrooma","starcatcher:shroomfish"],
    ["aquaculture:smallmouth_bass","starcatcher:sea_bass"],
    ["aquaculture:minnow","starcatcher:driftfin"],
    ["aquaculture:synodontis","starcatcher:lightning_bass"],
    ["aquaculture:tambaqui","starcatcher:dripfin"],
    ["aquaculture:tuna","starcatcher:bigeye_tuna"],
    ["aquaculture:perch","starcatcher:silverveil_perch"],
    ["aquaculture:pink_salmon","starcatcher:pink_koi"],
    ["aquaculture:piranha","starcatcher:hollowbelly_darter"],
    ["aquaculture:pollock","starcatcher:crystalback_boreal"],
    ["aquaculture:rainbow_trout","starcatcher:rose_siamese_fish"],
    ["aquaculture:catfish","starcatcher:sludge_catfish"],
    ["aquaculture:gar","starcatcher:downfall_bream"],
    ["aquaculture:goldfish","starcatcher:gold_fan"],
    ["netherdepthsupgrade:searing_cod", "starcatcher:pyrotrout"],
    ["netherdepthsupgrade:blazefish", "starcatcher:magma_fish"],
    ["netherdepthsupgrade:lava_pufferfish", "starcatcher:glowstone_pufferfish"],
    ["netherdepthsupgrade:obsidianfish", "starcatcher:obsidian_crab"],
    ["netherdepthsupgrade:bonefish", "starcatcher:scalding_pike"],
    ["netherdepthsupgrade:wither_bonefish", "starcatcher:embergill"],
    ["netherdepthsupgrade:magmacubefish",  "starcatcher:glowstone_seeker"],
    ["netherdepthsupgrade:glowdine", "starcatcher:suneater"],
    ["netherdepthsupgrade:soulsucker", "starcatcher:willish"],
    ["netherdepthsupgrade:fortress_grouper",  "starcatcher:black_eel"],
    ["netherdepthsupgrade:eyeball_fish", "starcatcher:willish"],
])