global.cobblemonfishPool = [
    { pokemon: "squirtle", weight: 2, lvlRange: [5,15], tiers: ['rare', 'epic'], seasons:['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "wartortle", weight: .75, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "blastoise", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "psyduck", weight: 25, lvlRange: [5,35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring'], waterTypes: ['fresh', 'river']},
    { pokemon: "golduck", weight: 15, lvlRange: [15,40], tiers: ['uncommon','rare'], seasons: ['spring', 'summer'], waterTypes: ['fresh','river']},
    { pokemon: "poliwag", weight: 25, lvlRange: [5,30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring, summer'], waterTypes: ['fresh', 'river']},
    { pokemon: "poliwhirl", weight: 10, lvlRange: [25,40], tiers: ['uncommon', 'rare'], seasons:['summer', 'autumn'], waterTypes: ['fresh', 'river']},
    { pokemon: "tentacool", weight: 30, lvlRange: [10,35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean']},
    { pokemon: "tentacruel", weight: 10, lvlRange: [30,50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean']},
    { pokemon: "slowpoke", weight: 15, lvlRange: [5,30], tiers: ['common', 'uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowpoke", weight: 15, lvlRange: [5,30], tiers: ['common', 'uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river'], variant:['galarian']},
    { pokemon: "slowbro", weight: 5, lvlRange: [37,50], tiers: ['uncommon','rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowbro", weight: 5, lvlRange: [37,50], tiers: ['uncommon','rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river'], variant:['galarian']},
    { pokemon: "seel", weight: 20, lvlRange: [5,30], tiers:['common','uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean','river']},
    { pokemon: "dewgong", weight: 5, lvlRange: [35,50], tiers:['uncommon','rare','epic'], seasons: ['winter'], waterTypes: ['ocean','river']},
    { pokemon: "grimer", weight: 10, lvlRange: [5,30], tiers:['common','uncommon','rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "muk", weight: 5, lvlRange: [40,50], tiers:['uncommon','rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "shellder", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "cloyster", weight: 5, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "krabby", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean, river']},
    { pokemon: "kingler", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "horsea", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "seadra", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare','epic'], seasons: ['autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "goldeen", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean','river']},
    { pokemon: "seaking", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare','epic'], seasons: ['spring','summer'], waterTypes: ['ocean','river']},
    { pokemon: "staryu", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "starmie", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "magikarp", weight: 80, lvlRange: [3,7], tiers: ['common'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "magikarp", weight: 30, lvlRange: [3,7], tiers: ['uncommon'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "gyarados", weight: 5, lvlRange: [20,40], tiers: ['rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "lapras", weight: 1, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "dratini", weight: 1, lvlRange: [5,30], tiers:['rare','epic'], seasons: ['autumn'], waterTypes: ['river','fresh']},
    { pokemon: "dragonair", weight: 0.5, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['autumn'], waterTypes: ['river','fresh']},
    { pokemon: "totodile", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "croconaw", weight: .75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "feraligatr", weight: .25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "chinchou", weight: 10, lvlRange: [10,30], tiers: ['common','uncommon','rare'], seasons: ['autumn'], waterTypes: ['ocean']},
    { pokemon: "lanturn", weight: 5, lvlRange: [25,40], tiers: ['uncommon','rare'], seasons: ['autumn'], waterTypes: ['ocean']},
    { pokemon: "politoed", weight: 10, lvlRange: [41,50], tiers: ['rare','epic'], seasons: ['autumn'], waterTypesr: ['ocean']},
    { pokemon: "wooper", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "wooper", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river'], variant: ['paldean']},
    { pokemon: "quagsire", weight: 5, lvlRange: [20,40], tiers: ['uncommon','rare'], seasons:['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowking", weight: 1, lvlRange: [35,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowking", weight: 1, lvlRange: [35,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river'], variant: ['galarian']},
    { pokemon: "qwilfish", weight: 15, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "qwilfish", weight: 15, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river'], variant:['hisuian']},
    { pokemon: "shuckle", weight: 20, lvlRange: [5,50], tiers: ['common','uncommon'], seasons: ['spring','summer'], waterTypes: ['river','fresh']},
    { pokemon: "corsola", weight: 20, lvlRange: [15,40], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "remoraid", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "octillery", weight: 5, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "mantine", weight: 15, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "kingdra", weight: 1, lvlRange: [40,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "mudkip", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "marshtomp", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "swampert", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "lotad", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "lombre", weight: 10, lvlRange: [15,30], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "ludicolo", weight: 2, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "carvanha", weight: 20, lvlRange: [5,30], tiers: ['uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean']},
    { pokemon: "sharpedo", weight: 10, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean']},
    { pokemon: "wailmer", weight: 20, lvlRange: [15,25], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "wailord", weight: 2, lvlRange: [40,50], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "barboach", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "whiscash", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "corphish", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    // { pokemon: "crawdaunt", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "feebas", weight: 2, lvlRange: [3,7], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "milotic", weight: 0.25, lvlRange: [15,50], tiers: ['epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "spheal", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "sphealeo", weight: 10, lvlRange: [30,40], tiers: ['uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "walrein", weight: 1, lvlRange: [40,50], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean']},
]