console.info("[SOCIETY-S-COBBLEMON] cobblemonFishingPool.js loaded");

global.cobblemonfishPool = [
    { pokemon: "squirtle", weight: 2, lvlRange: [5,15], tiers: ['rare', 'epic'], seasons:['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "wartortle", weight: .75, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "blastoise", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river']},
    { pokemon: "psyduck", weight: 25, lvlRange: [5,35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring'], waterTypes: ['fresh', 'river']},
    { pokemon: "golduck", weight: 15, lvlRange: [15,40], tiers: ['uncommon','rare'], seasons: ['spring', 'summer'], waterTypes: ['fresh','river']},
    { pokemon: "poliwag", weight: 25, lvlRange: [5,30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring, summer'], waterTypes: ['fresh', 'river']},
    { pokemon: "poliwhirl", weight: 10, lvlRange: [25,40], tiers: ['uncommon', 'rare'], seasons:['summer', 'autumn'], waterTypes: ['fresh', 'river']},
    { pokemon: "tentacool", weight: 30, lvlRange: [10,35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean']},
    { pokemon: "tentacruel", weight: 10, lvlRange: [30,50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean']},
    { pokemon: "slowpoke", weight: 15, lvlRange: [5,30], tiers: ['common', 'uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowpoke", weight: 15, lvlRange: [5,30], tiers: ['common', 'uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river'], variant:['galarian']},
    { pokemon: "slowbro", weight: 5, lvlRange: [37,50], tiers: ['uncommon','rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowbro", weight: 5, lvlRange: [37,50], tiers: ['uncommon','rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river'], variant:['galarian']},
    { pokemon: "seel", weight: 20, lvlRange: [5,30], tiers:['common','uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean','river']},
    { pokemon: "dewgong", weight: 5, lvlRange: [35,50], tiers:['uncommon','rare','epic'], seasons: ['winter'], waterTypes: ['ocean','river']},
    { pokemon: "grimer", weight: 10, lvlRange: [5,30], tiers:['common','uncommon','rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "muk", weight: 5, lvlRange: [40,50], tiers:['uncommon','rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "shellder", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "cloyster", weight: 5, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "krabby", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean, river']},
    { pokemon: "kingler", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "horsea", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "seadra", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare','epic'], seasons: ['autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "goldeen", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean','river']},
    { pokemon: "seaking", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare','epic'], seasons: ['spring','summer'], waterTypes: ['ocean','river']},
    { pokemon: "staryu", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "starmie", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "magikarp", weight: 80, lvlRange: [3,7], tiers: ['common'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "magikarp", weight: 30, lvlRange: [3,7], tiers: ['uncommon'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "gyarados", weight: 5, lvlRange: [20,40], tiers: ['rare'], seasons: ['spring','summer','autumn','winter'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "lapras", weight: 1, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "dratini", weight: 1, lvlRange: [5,30], tiers:['rare','epic'], seasons: ['autumn'], waterTypes: ['river','fresh']},
    { pokemon: "dragonair", weight: 0.5, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['autumn'], waterTypes: ['river','fresh']},
    { pokemon: "totodile", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "croconaw", weight: .75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "feraligatr", weight: .25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river']},
    { pokemon: "chinchou", weight: 10, lvlRange: [10,30], tiers: ['common','uncommon','rare'], seasons: ['autumn'], waterTypes: ['ocean']},
    { pokemon: "lanturn", weight: 5, lvlRange: [25,40], tiers: ['uncommon','rare'], seasons: ['autumn'], waterTypes: ['ocean']},
    { pokemon: "politoed", weight: 10, lvlRange: [41,50], tiers: ['rare','epic'], seasons: ['autumn'], waterTypesr: ['ocean']},
    { pokemon: "wooper", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "wooper", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river'], variant: ['paldean']},
    { pokemon: "quagsire", weight: 5, lvlRange: [20,40], tiers: ['uncommon','rare'], seasons:['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowking", weight: 1, lvlRange: [35,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "slowking", weight: 1, lvlRange: [35,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['fresh','river'], variant: ['galarian']},
    { pokemon: "qwilfish", weight: 15, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "qwilfish", weight: 15, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river'], variant:['hisuian']},
    { pokemon: "shuckle", weight: 20, lvlRange: [5,50], tiers: ['common','uncommon'], seasons: ['spring','summer'], waterTypes: ['river','fresh']},
    { pokemon: "corsola", weight: 20, lvlRange: [15,40], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "remoraid", weight: 15, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "octillery", weight: 5, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    // { pokemon: "mantine", weight: 15, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "kingdra", weight: 1, lvlRange: [40,50], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "mudkip", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "marshtomp", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "swampert", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "lotad", weight: 25, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "lombre", weight: 10, lvlRange: [15,30], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "ludicolo", weight: 2, lvlRange: [30,50], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "carvanha", weight: 20, lvlRange: [5,30], tiers: ['uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean']},
    { pokemon: "sharpedo", weight: 10, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer'], waterTypes: ['ocean']},
    { pokemon: "wailmer", weight: 20, lvlRange: [15,25], tiers: ['common','uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "wailord", weight: 2, lvlRange: [40,50], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "barboach", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "whiscash", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean','river','fresh']},
    // { pokemon: "corphish", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    // { pokemon: "crawdaunt", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "feebas", weight: 2, lvlRange: [3,7], tiers: ['rare','epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "milotic", weight: 0.25, lvlRange: [15,50], tiers: ['epic'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    // { pokemon: "spheal", weight: 20, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['winter'], waterTypes: ['ocean']},
    // { pokemon: "sphealeo", weight: 10, lvlRange: [30,40], tiers: ['uncommon','rare'], seasons: ['winter'], waterTypes: ['ocean']},
    // { pokemon: "walrein", weight: 1, lvlRange: [40,50], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "clamperl", weight: 15, lvlRange: [10,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "huntail", weight: 5, lvlRange: [30,40], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "gorebyss", weight: 5, lvlRange: [30,40], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "relicanth", weight: 2, lvlRange: [20,40], tiers: ['uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "luvdisc", weight: 10, lvlRange: [5,30], tiers: ['common','uncommon','rare'], seasons: ['summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "piplup", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "prinplup", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "empoleon", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "buizel", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "floatzel", weight: 5, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "shellos", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "gastrodon", weight: 2, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "finneon", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "lumineon", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "mantyke", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "oshawott", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "dewott", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "samurott", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh']},
    { pokemon: "samurott", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh'], variant: ['hisuian']},
    { pokemon: "basculin", weight: 20, lvlRange: [5,20], tiers: ['common'], seasons: ['spring','summer','autumn'], waterTypes: ['river','fresh','ocean']},
    { pokemon: "frillish", weight: 10, lvlRange: [10,30], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "jellicent", weight: 5, lvlRange: [40,50], tiers: ['rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "alomomola", weight: 5, lvlRange: [20,40], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "froakie", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "frogadier", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "greninja", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh']},
    { pokemon: "binacle", weight: 5, lvlRange: [5,30], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "barbaracle", weight: 2, lvlRange: [30,50], tiers: ['rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "skrelp", weight: 10, lvlRange: [5,30], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "dragalge", weight: 5, lvlRange: [5,30], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "clauncher", weight: 10, lvlRange: [5,30], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "clawitzer", weight: 2, lvlRange: [5,30], tiers: ['rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "goomy", weight: 1, lvlRange: [5,30], tiers: ['rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "bergmite", weight: 5, lvlRange: [5,30], tiers: ['uncommon'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "popplio", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['summer'], waterTypes: ['ocean','river']},
    { pokemon: "brionne", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['ocean','river']},
    { pokemon: "primarina", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['ocean','river']},
    { pokemon: "wishiwashi", weight: 15, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "mareanie", weight: 5, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "toxapex", weight: 2, lvlRange: [25,50], tiers: ['uncommon','rare'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "dewpider", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "araquanid", weight: 5, lvlRange: [25,40], tiers: ['uncommon','rare'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean','river','fresh']},
    { pokemon: "pyukumuku", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "bruxish", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "dhelmise", weight: 10, lvlRange: [5,20], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "sobble", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['spring','autumn','summer'], waterTypes: ['fresh']},
    { pokemon: "drizzile", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring','autumn','summer'], waterTypes: ['fresh']},
    { pokemon: "inteleon", weight: 0.25, lvlRange: [36,50], tiers: ['epic'], seasons: ['spring','autumn','summer'], waterTypes: ['fresh']},
    { pokemon: "barraskewda", weight: 10, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "pincurchin", weight: 10, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['spring','autumn','summer'], waterTypes: ['ocean']},
    { pokemon: "eiscue", weight: 10, lvlRange: [5,30], tiers: ['common','uncommon'], seasons: ['winter'], waterTypes: ['ocean']},
    { pokemon: "dreepy", weight: 1, lvlRange: [5,30], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "quaxly", weight: 2, lvlRange: [5,15], tiers: ['rare','epic'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "quaxwell", weight: 0.75, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "quaquaval", weight: 0.25, lvlRange: [16,35], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['fresh','river']},
    { pokemon: "finizen", weight: 5, lvlRange: [5,35], tiers: ['common','uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['river','ocean']},
    { pokemon: "palafin", weight: 2, lvlRange: [40,50], tiers: ['epic'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean','river']},
    { pokemon: "veluza", weight: 15, lvlRange: [20,40], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "tatsugiri", weight: 15, lvlRange: [20,30], tiers: ['uncommon'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']},
    { pokemon: "dondozo", weight: 2, lvlRange: [30,40], tiers: ['rare'], seasons: ['spring','summer','autumn'], waterTypes: ['ocean']}
]

global.cobblemonNetherFishPool = [
    { pokemon: "charmander", weight: 2, lvlRange: [5,15], tiers: ['rare', 'epic']},
    { pokemon: "charmeleon", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "charizard", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "growlithe", weight: 5, lvlRange: [5,35], tiers: ['common','uncommon']},
    { pokemon: "arcanine", weight: 0.5, lvlRange: [35,50,], tiers: ['uncommon','rare']},
    { pokemon: "ponyta", weight: 5, lvlRange: [5,35], tiers: ['common','uncommon']},
    { pokemon: "rapidash", weight: 0.5, lvlRange: [25,50], tiers: ['uncommon','rare']},
    { pokemon: "magby", weight: 10, lvlRange: [5,15], tiers: ['common','uncommon']},
    { pokemon: "mahgmar", weight: 5, lvlRange: [16,30], tiers: ['common','uncommon']},
    { pokemon: "magmortar", weight: 2, lvlRange: [35,50], tiers: ['rare']},
    { pokemon: "flareon", weight: 5, lvlRange: [5,35], tiers: ['uncommon','rare']},
    { pokemon: "cyndaquil", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "quilava", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "typhlosion", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "slugma", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon','rare']},
    { pokemon: "magcargo", weight: 5, lvlRange: [36,50], tiers: ['uncommon','rare']},
    { pokemon: "torchic", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "combusken", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "blaziken", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "numel", weight: 25, lvlRange: [5,30], tiers: ['common','uncommon']},
    { pokemon: "camerupt", weight: 0.25, lvlRange: [36,50], tiers: ['rare','epic']},
    { pokemon: "torkoal", weight: 5, lvlRange: [5,30], tiers: ['rare','uncommon']},
    { pokemon: "chimchar", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "monferno", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "infernape", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "tepig", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "pignite", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "emboar", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "litwick", weight: 10, lvlRange: [5,40], tiers: ['uncommon','common']},
    { pokemon: "lampent", weight: 5, lvlRange: [41,50], tiers: ['uncommon','rare']},
    { pokemon: "chandelure", weight: 2, lvlRange: [42,50], tiers: ['uncommon','rare']},
    { pokemon: "heatmor", weight: 10, lvlRange: [5,50], tiers: ['uncommon','common']},
    { pokemon: "larvesta", weight: 10, lvlRange: [5,50], tiers: ['uncommon','common']},
    { pokemon: "volcarona", weight: 5, lvlRange: [50,60], tiers: ['rare','epic']},
    { pokemon: "fennekin", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "braixen", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "delphox", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "litten", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "torracat", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "incineroar", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "salandit", weight: 5, lvlRange: [5,30], tiers: ['common','uncommon'], gender: ['male']},
    { pokemon: "salandit", weight: 0.5, lvlRange: [5,30], tiers: ['common','uncommon'], gender: ['female']},
    { pokemon: "salazzle", weight: 0.5, lvlRange: [33,50], tiers: ['rare'], gender: ['female']},
    { pokemon: "turtonator", weight: 2, lvlRange: [42,50], tiers: ['uncommon','rare']},
    { pokemon: "scorbunny", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "raboot", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "cinderace", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "sizzlipede", weight: 25, lvlRange: [5,25], tiers: ['common','uncommon']},
    { pokemon: "centiskorch", weight: 5, lvlRange: [30,50], tiers: ['uncommon','rare']},
    { pokemon: "fuecoco", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "crocalor", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "skeledirge", weight: 0.25, lvlRange: [36,50], tiers: ['epic']},
    { pokemon: "charcadet", weight: 2, lvlRange: [5,15], tiers: ['rare','epic']},
    { pokemon: "ceruledge", weight: 0.75, lvlRange: [16,35], tiers: ['epic']},
    { pokemon: "armarouge", weight: 0.75, lvlRange: [16,35], tiers: ['epic']}
]