// priority: -21
global.cobbleAdventuring = [
  { item: "cobblemon:relic_coin", value: 64 },
  { item: "cobblemon:relic_coin_pouch", value: 576 },
  { item: "cobblemon:relic_coin_sack", value: 5184 },
  { item: "cobblemon:helix_fossil", value: 920 },
  { item: "cobblemon:dome_fossil", value: 9200 },
  { item: "cobblemon:old_amber_fossil", value: 920 },
  { item: "cobblemon:root_fossil", value: 1204 },
  { item: "cobblemon:claw_fossil", value: 1204 },
  { item: "cobblemon:skull_fossil", value: 920 },
  { item: "cobblemon:armor_fossil", value: 1290 },
  { item: "cobblemon:cover_fossil", value: 5999 },
  { item: "cobblemon:plume_fossil", value: 920 },
  { item: "cobblemon:jaw_fossil", value: 8200 },
  { item: "cobblemon:sail_fossil", value: 8200 },
  { item: "cobblemon:fossilized_bird", value: 10000 },
  { item: "cobblemon:fossilized_fish", value: 10000 },
  { item: "cobblemon:fossilized_drake", value: 10000 },
  { item: "cobblemon:fossilized_dino", value: 10000 },
];
global.cobbleGeology = [
  { item: "cobblemon:tumblestone", value: 8 },
  { item: "cobblemon:black_tumblestone", value: 12 },
  { item: "cobblemon:sky_tumblestone", value: 16 },
  { item: "cobblemon:tumblestone_block", value: 32 },
  { item: "cobblemon:black_tumblestone_block", value: 48 },
  { item: "cobblemon:sky_tumblestone_block", value: 64 },
  { item: "cobblemon:normal_gem", value: 512 },
  { item: "cobblemon:fire_gem", value: 512 },
  { item: "cobblemon:water_gem", value: 512 },
  { item: "cobblemon:grass_gem", value: 512 },
  { item: "cobblemon:electric_gem", value: 512 },
  { item: "cobblemon:ice_gem", value: 512 },
  { item: "cobblemon:fighting_gem", value: 512 },
  { item: "cobblemon:poison_gem", value: 512 },
  { item: "cobblemon:ground_gem", value: 512 },
  { item: "cobblemon:flying_gem", value: 512 },
  { item: "cobblemon:psychic_gem", value: 512 },
  { item: "cobblemon:bug_gem", value: 512 },
  { item: "cobblemon:rock_gem", value: 512 },
  { item: "cobblemon:ghost_gem", value: 512 },
  { item: "cobblemon:dragon_gem", value: 512 },
  { item: "cobblemon:dark_gem", value: 512 },
  { item: "cobblemon:steel_gem", value: 512 },
  { item: "cobblemon:fairy_gem", value: 512 },
  { item: "cobblemon:fire_stone", value: 2048 },
  { item: "cobblemon:water_stone", value: 820 },
  { item: "cobblemon:thunder_stone", value: 500 },
  { item: "cobblemon:leaf_stone", value: 640 },
  { item: "cobblemon:moon_stone", value: 230 },
  { item: "cobblemon:sun_stone", value: 500 },
  { item: "cobblemon:shiny_stone", value: 1200 },
  { item: "cobblemon:dusk_stone", value: 1800 },
  { item: "cobblemon:dawn_stone", value: 806 },
  { item: "cobblemon:ice_stone", value: 1020 },
];

global.cobbleCrops = [
  { item: "cobblemon:big_root", value: 4 },
  { item: "cobblemon:energy_root", value: 16 },
  { item: "cobblemon:medicinal_leek", value: 2 },
  { item: "cobblemon:red_apricorn", value: 8 },
  { item: "cobblemon:yellow_apricorn", value: 8 },
  { item: "cobblemon:green_apricorn", value: 8 },
  { item: "cobblemon:blue_apricorn", value: 8 },
  { item: "cobblemon:pink_apricorn", value: 8 },
  { item: "cobblemon:black_apricorn", value: 8 },
  { item: "cobblemon:white_apricorn", value: 8 },
  { item: "cobblemon:white_mint_leaf", value: 44 },
  { item: "cobblemon:green_mint_leaf", value: 44 },
  { item: "cobblemon:pink_mint_leaf", value: 44 },
  { item: "cobblemon:cyan_mint_leaf", value: 44 },
  { item: "cobblemon:blue_mint_leaf", value: 44 },
  { item: "cobblemon:red_mint_leaf", value: 44 },
  { item: "cobblemon:vivichoke", value: 46 },
  { item: "cobblemon:revival_herb", value: 52 },
  { item: "cobblemon:mirror_herb", value: 120 },
  { item: "cobblemon:mental_herb", value: 100 },
  { item: "cobblemon:power_herb", value: 100 },
  { item: "cobblemon:white_herb", value: 100 },
  { item: "cobblemon:oran_berry", value: 4 },
  { item: "cobblemon:cheri_berry", value: 4 },
  { item: "cobblemon:chesto_berry", value: 4 },
  { item: "cobblemon:pecha_berry", value: 4 },
  { item: "cobblemon:rawst_berry", value: 4 },
  { item: "cobblemon:aspear_berry", value: 4 },
  { item: "cobblemon:persim_berry", value: 4 },
  { item: "cobblemon:razz_berry", value: 4 },
  { item: "cobblemon:bluk_berry", value: 4 },
  { item: "cobblemon:nanab_berry", value: 4 },
  { item: "cobblemon:wepear_berry", value: 4 },
  { item: "cobblemon:pinap_berry", value: 4 },
  { item: "cobblemon:occa_berry", value: 4 },
  { item: "cobblemon:passho_berry", value: 4 },
  { item: "cobblemon:wacan_berry", value: 4 },
  { item: "cobblemon:rindo_berry", value: 4 },
  { item: "cobblemon:yache_berry", value: 4 },
  { item: "cobblemon:chople_berry", value: 4 },
  { item: "cobblemon:kebia_berry", value: 4 },
  { item: "cobblemon:shuca_berry", value: 4 },
  { item: "cobblemon:coba_berry", value: 4 },
  { item: "cobblemon:payapa_berry", value: 4 },
  { item: "cobblemon:tanga_berry", value: 4 },
  { item: "cobblemon:charti_berry", value: 4 },
  { item: "cobblemon:kasib_berry", value: 4 },
  { item: "cobblemon:haban_berry", value: 4 },
  { item: "cobblemon:colbur_berry", value: 4 },
  { item: "cobblemon:babiri_berry", value: 4 },
  { item: "cobblemon:chilan_berry", value: 4 },
  { item: "cobblemon:roseli_berry", value: 6 },
  { item: "cobblemon:leppa_berry", value: 8 },
  { item: "cobblemon:lum_berry", value: 8 },
  { item: "cobblemon:figy_berry", value: 8 },
  { item: "cobblemon:wiki_berry", value: 8 },
  { item: "cobblemon:mago_berry", value: 8 },
  { item: "cobblemon:aguav_berry", value: 8 },
  { item: "cobblemon:iapapa_berry", value: 8 },
  { item: "cobblemon:sitrus_berry", value: 12 },
  { item: "cobblemon:touga_berry", value: 12 },
  { item: "cobblemon:cornn_berry", value: 12 },
  { item: "cobblemon:magost_berry", value: 12 },
  { item: "cobblemon:rabuta_berry", value: 12 },
  { item: "cobblemon:nomel_berry", value: 12 },
  { item: "cobblemon:hopo_berry", value: 12 },
  { item: "cobblemon:enigma_berry", value: 16 },
  { item: "cobblemon:pomeg_berry", value: 16 },
  { item: "cobblemon:kelpsy_berry", value: 16 },
  { item: "cobblemon:qualot_berry", value: 16 },
  { item: "cobblemon:hondew_berry", value: 16 },
  { item: "cobblemon:grepa_berry", value: 16 },
  { item: "cobblemon:tamato_berry", value: 16 },
  { item: "cobblemon:spelon_berry", value: 16 },
  { item: "cobblemon:pamtre_berry", value: 16 },
  { item: "cobblemon:watmel_berry", value: 16 },
  { item: "cobblemon:durin_berry", value: 16 },
  { item: "cobblemon:belue_berry", value: 16 },
  { item: "cobblemon:kee_berry", value: 32 },
  { item: "cobblemon:maranga_berry", value: 32 },
  { item: "cobblemon:liechi_berry", value: 32 },
  { item: "cobblemon:ganlon_berry", value: 32 },
  { item: "cobblemon:salac_berry", value: 32 },
  { item: "cobblemon:petaya_berry", value: 32 },
  { item: "cobblemon:apicot_berry", value: 32 },
  { item: "cobblemon:lansat_berry", value: 32 },
  { item: "cobblemon:starf_berry", value: 32 },
  { item: "cobblemon:micle_berry", value: 32 },
  { item: "cobblemon:custap_berry", value: 32 },
  { item: "cobblemon:jaboca_berry", value: 32 },
  { item: "cobblemon:rowap_berry", value: 32 },
];
/**
 * Preserves
 * Formula: Ingredient * 20
 */
global.cobblemonPreserves = [
  { item: "sunlit_cobblemon:leek_preserves", value: 40 },
  { item: "sunlit_cobblemon:vivichoke_preserves", value: 1280 },
  { item: "sunlit_cobblemon:common_cobbleberry_preserves", value: 80 },
  { item: "sunlit_cobblemon:uncommon_cobbleberry_preserves", value: 200 },
  { item: "sunlit_cobblemon:rare_cobbleberry_preserves", value: 320 },
  { item: "sunlit_cobblemon:legendary_cobbleberry_preserves", value: 640 },
];
global.cobbleAdventuring.forEach((miscItem) => {
  const { item, value } = miscItem;
  global.trades.set(item, {
    value: value,
    multiplier: "shippingbin:meat_sell_multiplier",
  });
});
global.cobbleGeology.forEach((miscItem) => {
  const { item, value } = miscItem;
  global.trades.set(item, {
    value: value,
    multiplier: "shippingbin:gem_sell_multiplier",
  });
});
global.cobblemonPreserves.forEach((miscItem) => {
  const { item, value } = miscItem;
  global.trades.set(item, {
    value: value,
    multiplier: "shippingbin:wood_sell_multiplier",
  });
});
global.cobbleCrops.forEach((miscItem) => {
  const { item, value } = miscItem;
  global.trades.set(item, {
    value: value,
    multiplier: "shippingbin:crop_sell_multiplier",
  });
});
