// priority: -21
global.cobbleGeology = [
  { item: "cobblemon:helix_fossil", value: 920 },
  { item: "cobblemon:dome_fossil", value: 9200 },
  { item: "cobblemon:old_amber_fossil", value: 920 },
  { item: "cobblemon:root_fossil", value: 1204 },
  { item: "cobblemon:claw_fossil", value: 1204 },
  { item: "cobblemon:skull_fossil", value: 920 },
  { item: "cobblemon:armor_fossil", value: 1290 },
  { item: "cobblemon:cover_fossil", value: 5999 },
  { item: "cobblemon:plume_fossil", value: 920 },
  { item: "cobblemon:jaw_fossil", value: 9200 },
  { item: "cobblemon:sail_fossil", value: 9200 },
  { item: "cobblemon:fossilized_bird", value: 12096 },
  { item: "cobblemon:fossilized_fish", value: 12096 },
  { item: "cobblemon:fossilized_drake", value: 12096 },
  { item: "cobblemon:fossilized_dino", value: 12096 },
  { item: "cobblemon:tumblestone", value: 8 },
  { item: "cobblemon:black_tumblestone", value: 12 },
  { item: "cobblemon:sky_tumblestone", value: 16 },
  { item: "cobblemon:normal_gem", value: 512 },
  { item: "cobblemon:fire_gem", value: 512 },
  { item: "cobblemon:water_gem", value: 512 },
  { item: "cobblemon:grass_gem", value: 512 },
  { item: "cobblemon:electric_gem", value: 512 },
  { item: "cobblemon:ice_gem", value: 512 },
  { item: "cobblemon:fighting_gem", value: 512 },
  { item: "cobblemon:poison_gem", value: 512 },
  { item: "cobblemon:ground_gem", value: 512 },
  { item: "cobblemon:flying_gem", value: 512 },
  { item: "cobblemon:psychic_gem", value: 512 },
  { item: "cobblemon:bug_gem", value: 512 },
  { item: "cobblemon:rock_gem", value: 512 },
  { item: "cobblemon:ghost_gem", value: 512 },
  { item: "cobblemon:dragon_gem", value: 512 },
  { item: "cobblemon:dark_gem", value: 512 },
  { item: "cobblemon:steel_gem", value: 512 },
  { item: "cobblemon:fairy_gem", value: 512 },
  { item: "cobblemon:fire_stone", value: 2048 },
  { item: "cobblemon:water_stone", value: 820 },
  { item: "cobblemon:thunder_stone", value: 500 },
  { item: "cobblemon:leaf_stone", value: 640 },
  { item: "cobblemon:moon_stone", value: 230 },
  { item: "cobblemon:sun_stone", value: 500 },
  { item: "cobblemon:shiny_stone", value: 1200 },
  { item: "cobblemon:dusk_stone", value: 1800 },
  { item: "cobblemon:dawn_stone", value: 806 },
  { item: "cobblemon:ice_stone", value: 1020 },
];

global.cobbleGeology.forEach((miscItem) => {
  const { item, value } = miscItem;
  global.trades.set(item, {
    value: value,
    multiplier: "shippingbin:gem_sell_multiplier",
  });
});
