StartupEvents.registry("block", (event) => {

    // Placeholder stuff for SK
    event.create('extractinator:slush')
    event.create('minecraft:grass')
    event.create('moreminecarts:chiseled_organic_glass_pane')
    event.create('moreminecarts:chiseled_organic_glass')
    event.create('moreminecarts:organic_glass_pane')
    event.create('moreminecarts:organic_glass')
    event.create('society:blackstone_boulder')
    event.create('society:deepslate_iridium_ore')
    event.create('society:deepslate_sparkstone_ore')
    event.create('society:earth_crystal')
    event.create('society:end_stone_boulder')
    event.create('society:fire_quartz')
    event.create('society:geode_node')
    event.create('society:ice_boulder')
    event.create('society:iridium_ore')
    event.create('society:magma_geode_node')
    event.create('society:oak_supply_crate')
    event.create('society:omni_geode_node')
    event.create('society:palm_supply_crate')
    event.create('society:sandstone_boulder')
    event.create('society:skull_arid_sandstone').texture("atmospheric:block/arid_sandstone_top")
    event.create('society:skull_blackstone').texture("minecraft:block/blackstone")
    event.create('society:skull_cavern_teleporter')
    event.create('society:skull_end_stone').texture("minecraft:block/end_stone")
    event.create('society:skull_permafrost').texture("quark:block/permafrost")
    event.create('society:skull_sandstone').texture("minecraft:block/sandstone_top")
    event.create('society:skull_stone').texture("minecraft:block/stone")
    event.create('society:sparkstone_ore')
    event.create('society:spruce_supply_crate')
    event.create('society:stone_boulder')
    event.create('windswept:icicles')
    event.create("society:grimwood_supply_crate")
})
