StartupEvents.registry("block", (e) => {
  ['copperandtuffbackportcopperandtuffbackport:copper_door', 'copperandtuffbackportcopperandtuffbackport:copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:exposed_copper_door', 'copperandtuffbackportcopperandtuffbackport:exposed_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:weathered_copper_door', 'copperandtuffbackportcopperandtuffbackport:weathered_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:oxidized_copper_door', 'copperandtuffbackportcopperandtuffbackport:oxidized_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:waxed_copper_door', 'copperandtuffbackportcopperandtuffbackport:waxed_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:waxed_exposed_copper_door', 'copperandtuffbackportcopperandtuffbackport:waxed_exposed_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:waxed_weathered_copper_door', 'copperandtuffbackportcopperandtuffbackport:waxed_weathered_copper_trapdoor', 'copperandtuffbackportcopperandtuffbackport:waxed_oxidized_copper_door', 'copperandtuffbackportcopperandtuffbackport:waxed_oxidized_copper_trapdoor', 'trials:waxed_copper_grate_oxidized', 'trials:waxed_copper_bulb_oxidized', 'trials:waxed_chiseled_copper_oxidized', 'trials:waxed_copper_grate_weathered', 'trials:waxed_copper_bulb_weathered', 'trials:waxed_chiseled_copper_weathered', 'trials:waxed_copper_grate_exposed', 'trials:waxed_copper_bulb_exposed', 'trials:waxed_chiseled_copper_exposed', 'trials:waxed_copper_grate', 'trials:waxed_copper_bulb', 'trials:waxed_chiseled_copper', 'trials:copper_grate_oxidized', 'trials:copper_bulb_oxidized', 'trials:chiseled_copper_oxidized', 'trials:copper_grate_weathered', 'trials:copper_bulb_weathered', 'trials:copper_grate_exposed', 'trials:chiseled_copper_weathered', 'trials:copper_bulb_exposed', 'trials:chiseled_copper_exposed', 'trials:copper_grate', 'trials:copper_bulb', 'trials:chiseled_copper', 'trials:chiseled_tuff_bricks', 'trials:tuff_brick_wall', 'trials:tuff_brick_slab', 'trials:tuff_brick_stairs', 'trials:tuff_bricks', 'trials:polished_tuff_wall', 'trials:polished_tuff_slab', 'trials:polished_tuff_stairs', 'trials:polished_tuff', 'trials:chiseled_tuff', 'trials:tuff_stairs', 'trials:tuff_slab', 'trials:tuff_wall'].forEach((item) => {
    e.create(item)
      .soundType("stone")
      .resistance(1.0)
      .tagBlock("c:hidden_from_recipe_viewers")
      .model(`copperandtuffbackport:block/${item.path}`)
      .randomTick((tick) => {
        tick.block.set(`copperandtuffbackport:${item.path}`, tick.block.getProperties())
      })
  })
});
