
let translationKeys = {
    "00.translator.warning": "--------------------------------------------------------------------------------------------------------",
    "01.translator.warning": "                                                                                                        ",
    "02.translator.warning": "DO NOT EDIT THIS FILE MANUALLY. This was generated by: kubejs/server_scripts/datagen/generateTootlips.js",
    "03.translator.warning": "                                                                                                        ",
    "04.translator.warning": "--------------------------------------------------------------------------------------------------------",
    "05.translator.warning": "                                                                                                        "
};
const getTooltipPath = (itemId) => {
    let splitItem = itemId.split(":");
    return `${splitItem[0]}.${splitItem[1]}`;
}

const generateBulkStandardsTooltips = (items, tooltips) => {
    items.forEach((item) => {
        let path = getTooltipPath(item);
        tooltips.forEach((alwaysTip, alwaysIndex) => {
            translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = `<ltcolor>c=AAAAAA;${alwaysTip}</ltcolor>`;
        })
    })
}
const generateStandardTooltips = (tooltipArray) => {
    tooltipArray.forEach((entry) => {
        let path = getTooltipPath(entry.item);
        entry.tooltips.forEach((alwaysTip, alwaysIndex) => {
            translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = `<ltcolor>c=${entry.color ? entry.color : "AAAAAA"};${alwaysTip}</ltcolor>`;
        })
    })
}
const generateColorWrappedTooltip = (tooltipArray, hexColor, additionalAlwaysTooltip) => {
    tooltipArray.forEach((entry) => {
        let path = getTooltipPath(entry.item);
        entry.tooltips.forEach((alwaysTip, alwaysIndex) => {
            translationKeys[`tooltip.always.${path}.${alwaysIndex}`] = `<ltcolor>c=${hexColor};${alwaysTip}</ltcolor>`;
        })
        if (additionalAlwaysTooltip) translationKeys[`tooltip.always.${path}.${entry.tooltips.length}`] = additionalAlwaysTooltip;
    })
}
/**
 * Common Utilities - These are common phrases in tooltips like "Right Click to Use!"
 */
const RIGHT_CLICK_TO_READ = "<ltcolor>c=55FF55;Right click to learn this skill!</ltcolor>";
/**
 * Category Tooltips - These are often bulk additions that often category tooltips e.g Artifact
 */
const artifactTooltips = [
    { item: "society:froggy_helm", tooltips: ["There's a large tongue nestled inside"] },
    { item: "society:ribbit_drum", tooltips: ["Nitwit Ribbits love to bang on this"] },
    { item: "society:ribbit_gadget", tooltips: ["Some sort of wetware circuit"] },
    { item: "society:legendary_ink", tooltips: ["We love casting spells"] },
    { item: "society:holy_symbol", tooltips: ["A tribute from a higher power"] },
    { item: "society:ember_crystal_cluster", tooltips: ["Feels hot to the touch"] },
    { item: "society:living_flesh", tooltips: ["Writhing and unnatural"] },
    { item: "society:source_gem", tooltips: ["Derived from a Gold Sea Coin"] },
    { item: "society:spider_silk", tooltips: ["Meticulously textured by a Nerdy Spider"] },
    { item: "society:wheel_of_adaptation", tooltips: ["Was once used to summon a beast"] },
    { item: "society:token_of_unity", tooltips: ["I love making mazes! I'm going to design the biggest maze ever!"] },
    { item: "society:toy_train", tooltips: ["« Limited to 2 passengers : ants »"] },
    { item: "society:perfect_cherry", tooltips: ["It wants you to eat it"] },
    { item: "society:mini_oni_eye", tooltips: ["Fits nicely on a banana"] },
    { item: "society:glitched_vhs", tooltips: ['"Whispers: Don\'t rewind..."'] },
    { item: "society:production_science_pack", tooltips: ["What was it used to research?"] },
    { item: "society:beemonican_seal", tooltips: ["From the lost city of Beemonica"] },
    { item: "society:steamy_gadget", tooltips: ["An ancient handheld computer powered by steam. The word 'Uni' is ingraved on the back"] },
    { item: "society:amulet_of_light", tooltips: ["A very normal and holy pendant"] },
    { item: "society:aquamagical_dust", tooltips: ["Feels mystical and oceanic..."] },
    { item: "society:princess_hairbrush", tooltips: ["Scuffed from being used to hit someone"] },
    { item: "society:heart_of_neptunium", tooltips: ["It hums aquamagically"] },
    { item: "society:green_tea_honeycomb", tooltips: ["Filled with sticky bittersweet"] },
    { item: "society:giant_bandolier_belt", tooltips: ["Impossibly large, as if a giant wooly creature wore it over its shoulder"] },
    { item: "society:ancient_builders_tool", tooltips: ["Relic of the World-Shapers"] },
    { item: "society:red_wrench", tooltips: ["I swear I won't use it..."] }
];

generateColorWrappedTooltip(artifactTooltips, "AA00AA", "🪣 §7Artifact")
const bookTooltips = [
    { item: "society:alias_moss", tooltips: ["Mossberries can be found in any season."] },
    { item: "society:animal_fancy", tooltips: ["Increases affection gained from petting farm animals."] },
    { item: "society:banana_karenina", tooltips: ["Doubles Banana Tree output."] },
    { item: "society:brine_and_punishment", tooltips: ["Pickled items are worth 100% more."] },
    { item: "society:bluegigi_meridian", tooltips: ["Bluegill are now worth 666 §f●."] },
    { item: "society:hitting_hard_and_soft", tooltips: ["Melee attacks do an extra 4 damage."] },
    { item: "society:canadian_and_famous", tooltips: ["Tappers output double. Doesn't affect Auto-Tappers."] },
    { item: "society:first_aid_guide", tooltips: ["Halves the maximum fee and debt from death."] },
    { item: "society:intro_to_algorithms", tooltips: ["Mining Lead ore no longer causes Brain Damage clouds."] },
    { item: "society:no_name_for_the_sheep", tooltips: ["Naming animals grants an additional heart of affection."] },
    { item: "society:paradise_crop", tooltips: ["1 additional crop drop per harvest."] },
    { item: "society:slime_contain_protect", tooltips: ["Incubating a Slime Heart has a chance to give you a Slime Ticket."] },
    { item: "society:slouching_towards_artistry", tooltips: ["Artisan Hoppers have a chance to not consume Sparkstone when harvesting. The chance increases the longer the product took to make."] },
    { item: "society:debt_caverns", tooltips: ["Fainting in the Skull Cavern no longer costs a fee or adds to debt."] },
    { item: "society:phenomenology_of_treasure", tooltips: ["Artifacts and Relics are worth 200% more."] },
    { item: "society:frogs_bounty_bazaar", tooltips: ["Prize Tickets give double the prizes."] },
    { item: "society:bullfish_jobs", tooltips: ["The quality of fish taken out of Fish Ponds scales with population."] },
    { item: "society:wuthering_logs", tooltips: ["Trees have a 15% chance to drop Fire Logs when chopped."] },
    { item: "society:the_spark_also_rises", tooltips: ["Mining any ore drops Sparkstone."] },
    { item: "society:universal_methods_of_farming", tooltips: ["The Market sells all basic seeds in every season."] },
    { item: "society:the_quality_of_the_earth", tooltips: ["Quality impacts of non-fish farmer products on prices are doubled."] },
    { item: "society:the_red_and_the_black", tooltips: ["Geodes, loot crates, and Slot Machines drop one more item."] },
    { item: "society:pond_house_five", tooltips: ["Fish Ponds will ask for half the items."] },
    { item: "society:women_who_run_with_the_plushies", tooltips: ["Plushies will start at 2 hearts of affection. Increases rates of high quality Plushies."] },
    { item: "society:the_metamorphosize", tooltips: ["Impact of size on Butterfly/Moth prices are tripled."] },
];
generateColorWrappedTooltip(bookTooltips, "AAAAAA", RIGHT_CLICK_TO_READ)
let upgradeTooltipHex = "55FF55"
const wrapUpgradeKeyword = (word) => `</ltcolor><ltcolor>c=00AA00;${word}</ltcolor><ltcolor>c=${upgradeTooltipHex};`;
const upgradeTooltips = [
    { item: "society:ancient_cog", tooltips: [`Use on a ${wrapUpgradeKeyword("Seed Maker")} to give it a 5%% chance of producing an Ancient Fruit Seed.`] },
    { item: "society:pink_matter", tooltips: [`Use on an ${wrapUpgradeKeyword("Artisan Cheese Press")} to make it auto-age ${wrapUpgradeKeyword("Cheese Wheels")}.`] },
    { item: "society:stone_hand", tooltips: [`Use on a ${wrapUpgradeKeyword("Preserve Jar")} to decrease input amount by 2.`] },
    { item: "society:broken_clock", tooltips: [`Use on an ${wrapUpgradeKeyword("Aging Cask")} to decrease aging time by half.`] },
    { item: "society:black_opal", tooltips: [`Use on a ${wrapUpgradeKeyword("Crystalarium")} to give it a 10%% chance of producing pristine items.`] },
    { item: "society:enkephalin", tooltips: [`Use on a ${wrapUpgradeKeyword("Mayonnaise Machine")} to give it a 5%% chance of producing ${wrapUpgradeKeyword("Supreme Mayonnaise")}.`] },
    { item: "society:tiny_gnome", tooltips: [`Use on an ${wrapUpgradeKeyword("Artisan Loom")} to give it a 25%% chance of producing rare furniture.`] },
    { item: "society:ancient_roe", tooltips: [`Use on a ${wrapUpgradeKeyword("Fish Smoker")} to double output.`] },
    { item: "society:frosted_tip", tooltips: [`Use on a ${wrapUpgradeKeyword("Charging Rod")} to work and triple output in winter.`] },
    { item: "society:infinity_worm", tooltips: [`Use on a ${wrapUpgradeKeyword("Deluxe Worm Farm")} to let it work without inputs.`] },
    { item: "society:inserter", tooltips: [`Use on an ${wrapUpgradeKeyword("Ancient Cask")} to let it process 4 items at a time.`] },
    { item: "society:cordycep", tooltips: [`Use on a ${wrapUpgradeKeyword("Dehydrator")} to double ${wrapUpgradeKeyword("mushroom")} output.`] },
    { item: "society:gray_anatomy", tooltips: [`Use on a ${wrapUpgradeKeyword("Wine Keg")} to give it a 5%% chance of producing a ${wrapUpgradeKeyword("Relic Trove")}.`] },
    { item: "society:recycled_core", tooltips: [`Use on a ${wrapUpgradeKeyword("Recycling Machine")} to double most outputs.`] }
];
generateColorWrappedTooltip(upgradeTooltips, upgradeTooltipHex)
/**
 * Misc
 */
const miscTooltips = [
    { item: "simplerecall:recall_potion", tooltips: ["Teleports you to your spawn location."] },
    { item: "numismatics_utils:bank_meter", tooltips: ["Shows balance in Bank Terminal when worn in curio slot."] },
    { item: "society:fairy_dust", tooltips: ["Use on an Artisan Machine to progress it by 1 day."] },
    { item: "society:magic_rope", tooltips: ["Teleports you down a level in the Skull Cavern."] },
    { item: "society:magic_tunnel", tooltips: ["Teleports you to the nearest cave in the direction of the block you've clicked in the Skull Cavern."] },
    { item: "society_trading:auto_trader", tooltips: ["Allows you to automatically trade from all unlocked shops. Cannot trade for stock-limited or unlocked trades."] },
    { item: "society:invitation", tooltips: ["Invites a villager to your town and gives a block to set their home."]},
    { item: "unusualfishmod:ripper_tooth", tooltips: ["Threatens the fish in a Fish Pond into changing their active quest."]},
    { item: "society:river_jelly", tooltips: ["Fished up from River biomes."]},
    { item: "society:ocean_jelly", tooltips: ["Fished up from Ocean & Beach biomes."]},
    { item: "society:lava_jelly", tooltips: ["Fished up from lava pools."]},
];
generateStandardTooltips(miscTooltips)
generateBulkStandardsTooltips(['whimsy_deco:phone', 'whimsy_deco:black_phone', 'whimsy_deco:red_phone', 'whimsy_deco:blue_phone', 'tanukidecor:antique_phone'], ["Right click to call any unlocked villager and access their shop"])


JsonIO.write(`kubejs/assets/society_tooltips/lang/en_us.json`, translationKeys);

