#The maximum number of blocks that can be linked to a remote control at base. Can be increased by the Remote Control Capacity enchantment.
# Default: 5
# Range: > 1
maxLinkedBlocks = 5
#Block IDs of blocks that are blacklisted from working with the Remote Control
remoteControlBlacklist = []
#Block IDs of blocks that are whitelisted for working with the Remote Control, ignored if empty. Takes precedence over blacklist if non-empty.
remoteControlWhitelist = []
