
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				chicken = true
				panda = true
				villager = true
				skeleton_horse = true
				wandering_trader = true
				zombie_villager = true
				cow = true
				pig = true
				horse = true
				skeleton = true
				bat = true
				zombified_piglin = true
				zombie = true
				mooshroom = true
				witch = true
				armor_stand = true
				glow_squid = true
				spider = true
				creeper = true
				sheep = true
				player = true
				enderman = true
				experience_orb = true
				rabbit = true
				slime = true
				lightning_bolt = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.buzzier_bees]
				moobloom = true

			[light_sources.settings.entities.wildernature]
				squirrel = true
				minisheep = true
				flamingo = true
				bison = true
				boar = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.botania]
				mana_burst = true

			[light_sources.settings.entities.atmospheric]
				cochineal = true

			[light_sources.settings.entities.furniture]
				pells = true

			[light_sources.settings.entities.species]
				deflector_dummy = true
				limpet = true
				deepfish = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.untitledduckmod]
				duck = true

			[light_sources.settings.entities.quark]
				shiba = true
				forgotten = true
				toretoise = true
				stoneling = true

			[light_sources.settings.entities.longwings]
				moth = true
				butterfly = true

			[light_sources.settings.entities.farmlife]
				galliraptor = true
				domestic_tribull = true

			[light_sources.settings.entities.autumnity]
				turkey = true

			[light_sources.settings.entities.meadow]
				wooly_sheep = true
				wooly_cow = true
				water_buffalo = true

			[light_sources.settings.entities.snowpig]
				snow_pig = true

			[light_sources.settings.entities.hamsters]
				hamster = true

			[light_sources.settings.entities.splendid_slimes]
				splendid_slime = true

			[light_sources.settings.entities.unusualfishmod]
				deep_crawler = true
				shockcat = true
				prawn = true
				blindsailfin = true

			[light_sources.settings.entities.crittersandcompanions]
				leaf_insect = true

			[light_sources.settings.entities.windswept]
				chilled = true

			[light_sources.settings.entities.balloonbox]
				balloonbox = true

