[creativeModeTabs]
	enableCreativeModeTabs = false
	syncSelectedCreativeModeTab = false
	disabledCreativeModeTabs = ["minecraft:op_blocks"]
	showCreativeTabNameInSearchbar = true

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true

[miscellaneous]
	emiOnlyInRecipeBook = false
